### PR TITLE
Update test with Android example

### PR DESCRIPTION
**Pull request by Flash1232**
For those Droid boyz out there :)

### CODE REVIEW

**Comment by ddz** [comment]
Thank you for the PR! Do you have a sample URL, .enc file, and `hex(media_key)` string for a streaming file (one that isn't downloaded and saved)? I have that for iOS already in `main_test.go` and `testdata/` already to verify that the code and instructions work and want to have test coverage for Android also.

**Comment by Flash1232** [comment]
Thanks for reaching out! I did provide my own example and altered the test although I'm not familiar with Go and the test definitely hasn't gotten prettier. Also, the procedure is identical to your test scenario but I don't know under what circumstances the file will be preserved on the server. I've sent it s.t. it won't be downloaded by the recipient.

**Comment by ddz** [comment]
I rebased to my latest master and added some commits to cleanup a bit. Now it's ready to merge. Thanks again!

**Comment by Flash1232** [comment]
Glad to hear that. Nicely done and great job btw!

**Pull request merged**
